<?php

return [
    'games' => 'images/game/',
    'large-image-1' => '/large/game-large1.jpg',
    'large-image-2' => '/large/game-large2.jpg',
    'large-image-3' => '/large/game-large3.jpg',
    'large-image-4' => '/large/game-large4.jpg',
    'image-1' => '/game1.jpg',
    'image-2' => '/game2.jpg',
    'image-3' => '/game3.jpg',
    'image-4' => '/game4.jpg',
    'facebook' => 'https://www.google.com/search?q=facebook',
    'instagram' => 'https://www.google.com/search?q=instagram',
    'pinterest' => 'https://www.google.com/search?q=pinterest',
    'youtube' => 'https://www.google.com/search?q=youtube',
    'master-slide-09' => 'client/images/master-slide-09.jpg',
    'master-slide-10' => 'client/images/master-slide-10.jpg',
    'master-slide-11' => 'client/images/master-slide-11.jpg',
    'user-icon' => 'client/images/icons/icon-header-01.png',
    'cart-icon' => 'client/images/icons/icon-header-02.png',
    'game-detail-link' => 'client/images/games/',
    'blog-link' => 'client/images/blogs/',
    'logo' => 'client/images/icons/logo2.png',
];
